server:
  port: 5001
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/BankAccount?createDatabaseIfNotExistTrue
    username: root
    password: kuroi3112002
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      group-id: accountConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
